version: "3.7"
services:
  workspace:
    build: .
    image: nonfiction/workspace:latest
    env_file: .env
    volumes:
      # - cache:/cache
      # - data:/data
      # - /work:/work
      # - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: cache
        target: /cache
      - type: volume
        source: data
        target: /data
      - type: bind
        source: /work
        target: /work
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    restart: unless-stopped
    expose: 
      - 8443
      - 2222

volumes:
  cache:
  data:
