version: "3.7"
services:
  workspace:
    build: .
    image: nonfiction/workspace:latest
    env_file: .env
    volumes:
      - type: bind
        source: /work
        target: /work
      - type: volume
        source: share
        target: /usr/local/share
      - type: volume
        source: cache
        target: /usr/local/cache
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    restart: unless-stopped
    expose: 
      - 8443
      - 2222

volumes:
  cache:
  share:
