version: "3.7"
services:
  workspace:
    build: .
    image: nonfiction/workspace:latest
    env_file: .env
    volumes:
      - type: volume
        source: data
        target: /home/nonfiction/.local/share
      - type: volume
        source: work
        target: /home/nonfiction/work
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    restart: unless-stopped
    expose: 
      - 8443
      - 2222

volumes:
  data:
  work:
